In [1]:
import numpy as np

In [2]:
x=np.arange(1,14,3)

In [3]:
x

array([ 1,  4,  7, 10, 13])

* np.linspace(start, stop, N) 函数返回 N 个在闭区间 [start, stop] 内均匀分布的数字。

In [5]:
x=np.linspace(1,14,5)

In [6]:
x

array([  1.  ,   4.25,   7.5 ,  10.75,  14.  ])

* 使用 reshape

In [7]:
x=np.arange(10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.reshape(x,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 练习1：

Using the Built-in functions you learned about in the  
previous lesson, create a 4 x 4 ndarray that only  
contains consecutive even numbers from 2 to 32 (inclusive)

使用上一节课学到的内置函数，创建一个4×4的ndarray，它只包含从2到32的连续偶数(包括)

In [12]:
np.linspace(2,32,16).reshape(4,4)

array([[  2.,   4.,   6.,   8.],
       [ 10.,  12.,  14.,  16.],
       [ 18.,  20.,  22.,  24.],
       [ 26.,  28.,  30.,  32.]])

### 练习2：

import numpy as np

Create a 5 x 5 ndarray with consecutive（连续的） integers（整数） from 1 to 25 (inclusive).
Afterwards use Boolean indexing to pick out only the odd numbers in the array  
Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).  
然后使用布尔索引只挑出数组中的奇数  
创建一个5×5的ndarray，它具有从1到25(包含)的连续整数。  
X = 

Use Boolean indexing to pick out only the odd numbers in the array  
使用布尔索引只选择数组中的奇数  
Y = 


In [18]:
x=np.arange(1,26).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

* 注意此处使用了bool索引

In [19]:
y=x[x%2!=0]
y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])