## 1、ndarray

In [2]:
# 引入numpy
import numpy as np
#多维数组
array1=[6,7.5,8,0,1]
#通过array函数创建数组
data1=np.array(array1)
print(data1)
data1.shape

[ 6.   7.5  8.   0.   1. ]


(5,)

## 2嵌套序列


In [3]:
array2=[[1,2,3,4],[5,6,7,8,9]]
array21=[[1,2,3,4],[5,6,7,8]]
print(array2)
data2=np.array(array2)
print(data2)
print(np.array(array2))
array2
data2

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]


array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 9])], dtype=object)

## 3 查看类型

In [4]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
arr2
arr2.dtype


dtype('int64')

## 4 全0或全1数组

In [5]:
# 全0数组
np.zeros(10)
#
np.empty((2,3,2))
#对角线为1
# 的5*5方阵
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## 5 range 生成数组

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 5.1 ndarray的数据类型与显示转换

In [7]:
#转为浮点类型
arr1=np.array([1,2,3],dtype=np.float64)
print(arr1)
arr1.dtype
#显示类型转换
arr2=arr1.astype(np.int32)
print(arr2)

[ 1.  2.  3.]
[1 2 3]


## 6 数组和标量之间的运算

In [8]:
arr=np.array([[1,2,3,],[4,5,6]])
print(arr)
arr

# 自相乘
arr*arr
#每个位置上加2
arr+2

[[1 2 3]
 [4 5 6]]


array([[3, 4, 5],
       [6, 7, 8]])

## 7 基本的索引和切片

### 7.1 切片索引是浅拷贝

In [9]:
arr=np.arange(15)

print(arr)
# 索引从0开始计数
arr[3]
# 切片
# 参数1：起始位置下标
# 参数2：终止位置下标-1
# 数组切片是原始数组的视图
arr[3:5]=[100,101]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  0   1   2 100 101   5   6   7   8   9  10  11  12  13  14]


In [10]:
# 对数组进行副本复制
new_arr=arr[5:8].copy()
# 修改副本的值对原来的数组没有影响
new_arr[0]=300
print("new arr %s"%new_arr)
print("arr%s"%arr)

new arr [300   6   7]
arr[  0   1   2 100 101   5   6   7   8   9  10  11  12  13  14]


### 7.2 多维数组

In [11]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
# 取出索引为1的一行数据
arr2d[1]
# 取出二维数组中的某一个值
# 两种表现方式哪种都可以
arr2d[2,2]
arr2d[2][2]

9

#### (1)多维数组的切片索引

In [12]:
print(arr2d)
# 注意使用:x的方式x是下标减1的位置
arr2d[:2]
arr2d[:-2]
arr2d[:2,1:]
print(arr2d[1][:1])

# 选取第一列数据
arr2d[:,:1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4]


array([[1],
       [4],
       [7]])

## 8 布尔类型索引

In [13]:
names=np.array(['a1','b2','c3','d4','e5','f6','g7'])

# 使用names=='a1'的方式获取布尔数组索引
print(names=='a1')



data=np.random.randn(7,4)
print(data)

# 获取第一行数据
data[names=='a1']

# 将所有的data的随机数中小于0的部分设置为0
data[data<0]=0
print(data)

[ True False False False False False False]
[[-1.52449363 -0.42657572 -0.61751636 -2.30602187]
 [ 1.55021763  0.98504571 -0.14668741 -1.30704948]
 [ 2.30063019 -1.79683584 -1.14128861  0.31954925]
 [ 0.82558373 -1.50524895  1.12262885 -0.43117613]
 [ 0.65369794 -0.82616324  1.55768741 -0.10629156]
 [ 0.18427322  1.51844612  0.79021208  0.81408265]
 [ 0.35585999 -0.61949546 -0.40941181  1.41752074]]
[[ 0.          0.          0.          0.        ]
 [ 1.55021763  0.98504571  0.          0.        ]
 [ 2.30063019  0.          0.          0.31954925]
 [ 0.82558373  0.          1.12262885  0.        ]
 [ 0.65369794  0.          1.55768741  0.        ]
 [ 0.18427322  1.51844612  0.79021208  0.81408265]
 [ 0.35585999  0.          0.          1.41752074]]


### 9 花式索引
##### 花式索引指的是利用整数数组进行索引

In [14]:
arr=np.empty((8,3))
for i in range(8):
    arr[i]=i
print(arr)


[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]
 [ 6.  6.  6.]
 [ 7.  7.  7.]]


In [15]:
#以特定顺序选取子集
arr[[4,5,6]]

array([[ 4.,  4.,  4.],
       [ 5.,  5.,  5.],
       [ 6.,  6.,  6.]])

In [16]:
#32个顺序数，转乘8行4列
arr=np.arange(32).reshape((8,4))
print(arr)
# 若转乘9行4列（会出错）
#arr.reshape((9,4))
#print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [17]:
#转置
print(arr.T)


[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


### 10 通用函数
#### ufunc

In [18]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [20]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [21]:
x=np.random.randn(8)
y=np.random.randn(8)
print('x:%s'%x)
print('y:%s'%y)
# 取出两个数组中的每个位置的最大值
np.maximum(x,y)

x:[ 0.23275019  0.91738567  2.59110118 -0.9912314   0.48649179  0.10194464
  0.1365659  -0.81497701]
y:[ 0.5006741  -0.88001435 -1.01943095  1.36607929 -1.15029808  0.94081857
  0.13834246 -0.32153128]


array([ 0.5006741 ,  0.91738567,  2.59110118,  1.36607929,  0.48649179,
        0.94081857,  0.13834246, -0.32153128])

In [22]:
arr=np.random.randn(7)*5
arr

array([ -9.04057579, -10.5061512 ,  -4.69893015,  -0.56758464,
        -1.64334314,  -8.08519643,  -4.32474812])

In [23]:
np.modf(arr)

(array([-0.04057579, -0.5061512 , -0.69893015, -0.56758464, -0.64334314,
        -0.08519643, -0.32474812]),
 array([ -9., -10.,  -4.,  -0.,  -1.,  -8.,  -4.]))

In [24]:
# 计算绝对值
np.fabs(arr)

array([  9.04057579,  10.5061512 ,   4.69893015,   0.56758464,
         1.64334314,   8.08519643,   4.32474812])

### 11 利用数组进行数据处理
#### 利用数组表达式替换循环的做饭，通常被称为矢量化
矢量化数组运算效率较高

In [25]:
points=np.arange(-5,5,0.1)
points

array([ -5.00000000e+00,  -4.90000000e+00,  -4.80000000e+00,
        -4.70000000e+00,  -4.60000000e+00,  -4.50000000e+00,
        -4.40000000e+00,  -4.30000000e+00,  -4.20000000e+00,
        -4.10000000e+00,  -4.00000000e+00,  -3.90000000e+00,
        -3.80000000e+00,  -3.70000000e+00,  -3.60000000e+00,
        -3.50000000e+00,  -3.40000000e+00,  -3.30000000e+00,
        -3.20000000e+00,  -3.10000000e+00,  -3.00000000e+00,
        -2.90000000e+00,  -2.80000000e+00,  -2.70000000e+00,
        -2.60000000e+00,  -2.50000000e+00,  -2.40000000e+00,
        -2.30000000e+00,  -2.20000000e+00,  -2.10000000e+00,
        -2.00000000e+00,  -1.90000000e+00,  -1.80000000e+00,
        -1.70000000e+00,  -1.60000000e+00,  -1.50000000e+00,
        -1.40000000e+00,  -1.30000000e+00,  -1.20000000e+00,
        -1.10000000e+00,  -1.00000000e+00,  -9.00000000e-01,
        -8.00000000e-01,  -7.00000000e-01,  -6.00000000e-01,
        -5.00000000e-01,  -4.00000000e-01,  -3.00000000e-01,
        -2.00000000e-01,

In [26]:
xs,ys=np.meshgrid(points,points)
xs

array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       ..., 
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]])

In [27]:
import matplotlib.pyplot as plt
z=np.sqrt(xs**2+ys**2)
z
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()
plt.title("sss")

Text(0.5,1,'sss')

### 12 将条件逻辑表达为数组运算
#### numpy.where 函数是三元表达式 x if condition else y 的矢量化版本

In [28]:
x=np.array([1.1,1.2,1.3,1.4,1.5])
y=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
# 在满足cond的条件下时输出x，否则输出y
result=np.where(cond,x,y)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

####np.where通常用于根据另一个数组而产生一个新的数组

#### 对于一个随机数组，将所有正值替换为2，将所有负值替换为-2

In [32]:
arr=np.random.randn(4,4)
arr

array([[ 1.02326792, -2.15427197, -0.95201254, -1.33137164],
       [-0.03580436,  0.41944493, -0.66600247,  0.38642656],
       [-1.69453415, -1.76894473,  0.53448307, -0.36739347],
       [ 2.15848439,  0.97298775, -0.72192079,  0.12964882]])

In [33]:
# 将所有的正值替换为2，将所有的负值替换为02
np.where(arr>0,2,-2)

array([[ 2, -2, -2, -2],
       [-2,  2, -2,  2],
       [-2, -2,  2, -2],
       [ 2,  2, -2,  2]])

In [34]:
# 只将正值替换为2
np.where(arr>0,2,arr)

array([[ 2.        , -2.15427197, -0.95201254, -1.33137164],
       [-0.03580436,  2.        , -0.66600247,  2.        ],
       [-1.69453415, -1.76894473,  2.        , -0.36739347],
       [ 2.        ,  2.        , -0.72192079,  2.        ]])

### 数学和统计方法

In [36]:
arr=np.random.randn(5,4)
arr

array([[-0.47292944, -0.29446905,  0.41943032,  0.81342998],
       [-0.46246677, -0.08980346, -1.1202081 , -1.16299577],
       [-1.00087333, -0.54802667,  2.30757192,  0.32148645],
       [-0.40457002, -1.07346228,  0.65126653,  0.63109087],
       [ 0.18763668,  0.11524479, -1.28608528, -1.28996827]])

#### 正态分布函数的两种方式

In [40]:
arr.mean()

-0.18793504463143959

In [41]:
np.mean(arr)

-0.18793504463143959

#### 用于布尔型数组的方法

In [42]:
# 布尔值会被强制转换为1，sum函数经常被用来对布尔类型数组的true的计算

In [51]:
arr=np.random.randn(100)
arr
arr.sort()
arr

array([-2.89738022, -2.58144815, -2.36167579, -2.18886475, -2.02141635,
       -1.96444359, -1.82661842, -1.67639258, -1.37767384, -1.32324229,
       -1.31812582, -1.26475078, -1.19747002, -1.14805638, -1.02173073,
       -1.00030237, -0.98178219, -0.96150748, -0.86003592, -0.81470599,
       -0.76860228, -0.73564986, -0.68443189, -0.67960559, -0.63219411,
       -0.62507656, -0.60703733, -0.57808886, -0.54131446, -0.50147352,
       -0.42398504, -0.42240026, -0.38779673, -0.33750857, -0.27351867,
       -0.26725892, -0.23177154, -0.22940265, -0.19554936, -0.1806229 ,
       -0.15120152, -0.15026472, -0.13819205, -0.10468101, -0.07443991,
       -0.06847095, -0.06282737, -0.03241124,  0.02481734,  0.02623079,
        0.08390181,  0.11594777,  0.15844287,  0.17797498,  0.17863977,
        0.24083326,  0.26003683,  0.26166535,  0.27060743,  0.27615851,
        0.30016528,  0.30516057,  0.31169259,  0.34472104,  0.35153225,
        0.37767277,  0.40633399,  0.40930308,  0.41339768,  0.43

In [49]:
# 排序
print(arr.sort())

None


### 实例：随机漫步


In [10]:
import random
position=0
walk=[position]
steps=1000
# 注意在py3中py2中的xrange由range所替代
# range（steps) 从0开始生成到steps的数组
xr=range(steps)
for i in xr:
    step=1 if random.randint(0,1) else -1
    position+=step
    walk.append(position)
walk

[0,
 1,
 2,
 1,
 2,
 3,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 2,
 1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 -1,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 -1,
 0,
 1,
 0,
 -1,
 0,
 1,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 5,
 6,
 5,
 6,
 5,
 4,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 12,
 13,
 12,
 13,
 12,
 13,
 14,
 13,
 12,
 11,
 12,
 11,
 10,
 11,
 12,
 13,
 14,
 15,
 14,
 15,
 14,
 13,
 12,
 13,
 12,
 13,
 12,
 13,
 12,
 11,
 12,
 13,
 14,
 15,
 16,
 15,
 16,
 15,
 14,
 13,
 14,
 15,
 14,
 13,
 14,
 13,
 14,
 13,
 14,
 15,
 14,
 15,
 16,
 15,
 14,
 15,
 16,
 17,
 16,
 17,
 16,
 17,
 18,
 19,
 20,
 19,
 20,
 19,
 20,
 19,
 18,
 17,
 16,
 17,
 16,
 17,
 16,
 17,
 16,
 17,
 16,
 17,
 18,
 17,
 18,
 17,
 16,
 15,
 14,
 15,
 14,
 13,
 12,
 13,
 14,
 13,
 12,
 11,
 10,
 9,
 10,
 9

In [12]:
import numpy as np
# 实现随机漫步的方式二
nsteps=1000
draws=np.random.randint(0,2,size=nsteps)
steps=np.where(draws>0,1,-1)
# 求所有元素的累计和
# 数组当前值于之前值相加的和，组成一个新的数组
walk=steps.cumsum()
print(walk)
print(walk.min())
print(walk.max())

[  1   2   1   0   1   2   3   4   3   2   3   2   3   4   5   4   5   4
   3   4   3   4   5   6   5   6   7   6   7   6   5   6   7   8   9  10
  11  10   9   8   7   8   9  10   9   8   9  10   9  10  11  12  11  10
   9  10   9   8   9   8   9   8   7   8   7   8   7   6   5   4   5   4
   5   4   5   4   3   4   5   6   5   6   5   4   3   2   1   2   1   0
  -1  -2  -1   0   1   2   1   0  -1  -2  -3  -4  -3  -2  -1   0  -1  -2
  -3  -2  -3  -2  -3  -4  -3  -4  -3  -4  -3  -2  -3  -4  -5  -4  -3  -2
  -1  -2  -1   0   1   2   1   0  -1  -2  -3  -2  -1  -2  -1  -2  -1  -2
  -1  -2  -3  -2  -3  -4  -5  -6  -5  -4  -3  -4  -3  -2  -1   0   1   2
   1   2   3   4   3   2   1   2   3   4   5   6   7   6   7   6   5   4
   3   2   3   4   3   4   5   4   5   4   5   4   3   2   1   2   1   2
   1   2   3   4   3   4   5   6   5   4   3   4   3   2   3   2   3   4
   3   2   3   2   1   0  -1   0   1   0   1   0  -1  -2  -3  -2  -3  -2
  -1  -2  -3  -4  -3  -4  -5  -4  -3  -2  -3  -2  -

#### 一次模拟多个随机漫步

In [14]:
nwalks=5000
nsteps=1000
draws=np.random.randint(0,2,size=(nwalks,nsteps))
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)
print(walks)

[[  1   0  -1 ..., -12 -13 -14]
 [  1   0  -1 ...,  20  19  18]
 [  1   0  -1 ...,  32  33  34]
 ..., 
 [ -1  -2  -1 ...,  50  49  50]
 [ -1   0   1 ...,  14  13  12]
 [ -1  -2  -1 ..., -22 -23 -22]]
