## 1、ndarray

In [2]:
# 引入numpy
import numpy as np
#多维数组
array1=[6,7.5,8,0,1]
#通过array函数创建数组
data1=np.array(array1)
print(data1)
data1.shape

[ 6.   7.5  8.   0.   1. ]


(5,)

## 2嵌套序列


In [3]:
array2=[[1,2,3,4],[5,6,7,8,9]]
array21=[[1,2,3,4],[5,6,7,8]]
print(array2)
data2=np.array(array2)
print(data2)
print(np.array(array2))
array2
data2

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]


array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 9])], dtype=object)

## 3 查看类型

In [4]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
arr2
arr2.dtype


dtype('int64')

## 4 全0或全1数组

In [5]:
# 全0数组
np.zeros(10)
#
np.empty((2,3,2))
#对角线为1
# 的5*5方阵
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## 5 range 生成数组

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 5.1 ndarray的数据类型与显示转换

In [7]:
#转为浮点类型
arr1=np.array([1,2,3],dtype=np.float64)
print(arr1)
arr1.dtype
#显示类型转换
arr2=arr1.astype(np.int32)
print(arr2)

[ 1.  2.  3.]
[1 2 3]


## 6 数组和标量之间的运算

In [8]:
arr=np.array([[1,2,3,],[4,5,6]])
print(arr)
arr

# 自相乘
arr*arr
#每个位置上加2
arr+2

[[1 2 3]
 [4 5 6]]


array([[3, 4, 5],
       [6, 7, 8]])

## 7 基本的索引和切片

### 7.1 切片索引是浅拷贝

In [9]:
arr=np.arange(15)

print(arr)
# 索引从0开始计数
arr[3]
# 切片
# 参数1：起始位置下标
# 参数2：终止位置下标-1
# 数组切片是原始数组的视图
arr[3:5]=[100,101]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  0   1   2 100 101   5   6   7   8   9  10  11  12  13  14]


In [10]:
# 对数组进行副本复制
new_arr=arr[5:8].copy()
# 修改副本的值对原来的数组没有影响
new_arr[0]=300
print("new arr %s"%new_arr)
print("arr%s"%arr)

new arr [300   6   7]
arr[  0   1   2 100 101   5   6   7   8   9  10  11  12  13  14]


### 7.2 多维数组

In [11]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
# 取出索引为1的一行数据
arr2d[1]
# 取出二维数组中的某一个值
# 两种表现方式哪种都可以
arr2d[2,2]
arr2d[2][2]

9

#### (1)多维数组的切片索引

In [12]:
print(arr2d)
# 注意使用:x的方式x是下标减1的位置
arr2d[:2]
arr2d[:-2]
arr2d[:2,1:]
print(arr2d[1][:1])

# 选取第一列数据
arr2d[:,:1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4]


array([[1],
       [4],
       [7]])

## 8 布尔类型索引

In [16]:
names=np.array(['a1','b2','c3','d4','e5','f6','g7'])

# 使用names=='a1'的方式获取布尔数组索引
print(names=='a1')



data=np.random.randn(7,4)
print(data)

# 获取第一行数据
data[names=='a1']

# 将所有的data的随机数中小于0的部分设置为0
data[data<0]=0
print(data)

[ True False False False False False False]
[[ 1.2495287  -0.5586979  -0.24350244  0.07343661]
 [ 0.27689439 -0.66899711 -0.73927312  1.27232275]
 [-0.20050184  0.7440356   0.26018324  0.3550456 ]
 [ 1.40784522 -0.81016947  1.4161346  -0.44246957]
 [ 1.10762722  0.00370697 -1.90826832  2.05424114]
 [-0.90306399 -0.34247181  0.4211133  -0.39464871]
 [ 1.89268415  0.30593561 -0.59913626 -0.58823382]]
[[ 1.2495287   0.          0.          0.07343661]
 [ 0.27689439  0.          0.          1.27232275]
 [ 0.          0.7440356   0.26018324  0.3550456 ]
 [ 1.40784522  0.          1.4161346   0.        ]
 [ 1.10762722  0.00370697  0.          2.05424114]
 [ 0.          0.          0.4211133   0.        ]
 [ 1.89268415  0.30593561  0.          0.        ]]


### 9 花式索引
##### 花式索引指的是利用整数数组进行索引

In [21]:
arr=np.empty((8,3))
for i in range(8):
    arr[i]=i
print(arr)


[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]
 [ 6.  6.  6.]
 [ 7.  7.  7.]]


In [22]:
#以特定顺序选取子集
arr[[4,5,6]]

array([[ 4.,  4.,  4.],
       [ 5.,  5.,  5.],
       [ 6.,  6.,  6.]])

In [25]:
#32个顺序数，转乘8行4列
arr=np.arange(32).reshape((8,4))
print(arr)
# 若转乘9行4列（会出错）
#arr.reshape((9,4))
#print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


ValueError: cannot reshape array of size 32 into shape (9,4)

In [26]:
#转置
print(arr.T)


[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


### 10 通用函数
#### ufunc

In [28]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [30]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [35]:
x=np.random.randn(8)
y=np.random.randn(8)
print('x:%s'%x)
print('y:%s'%y)
# 取出两个数组中的每个位置的最大值
np.maximum(x,y)

x:[-1.3705126   0.26281251  0.93348455 -0.59363533  0.00615934 -0.9908788
  0.35374019  0.39730323]
y:[ 0.86115412 -0.44751232 -0.09044676 -0.58363013 -0.96724871 -2.08148727
  0.30665384 -0.70871145]


array([ 0.86115412,  0.26281251,  0.93348455, -0.58363013,  0.00615934,
       -0.9908788 ,  0.35374019,  0.39730323])

In [36]:
arr=np.random.randn(7)*5
arr

array([-1.18852304,  1.27243103, -7.585722  ,  0.90024784,  1.44111485,
       -7.85188686,  7.80093092])

In [37]:
np.modf(arr)

(array([-0.18852304,  0.27243103, -0.585722  ,  0.90024784,  0.44111485,
        -0.85188686,  0.80093092]), array([-1.,  1., -7.,  0.,  1., -7.,  7.]))

In [39]:
# 计算绝对值
np.fabs(arr)

array([ 1.18852304,  1.27243103,  7.585722  ,  0.90024784,  1.44111485,
        7.85188686,  7.80093092])

### 11 利用数组进行数据处理
#### 利用数组表达式替换循环的做饭，通常被称为矢量化
矢量化数组运算效率较高

In [41]:
points=np.arange(-5,5,0.1)
points

array([ -5.00000000e+00,  -4.90000000e+00,  -4.80000000e+00,
        -4.70000000e+00,  -4.60000000e+00,  -4.50000000e+00,
        -4.40000000e+00,  -4.30000000e+00,  -4.20000000e+00,
        -4.10000000e+00,  -4.00000000e+00,  -3.90000000e+00,
        -3.80000000e+00,  -3.70000000e+00,  -3.60000000e+00,
        -3.50000000e+00,  -3.40000000e+00,  -3.30000000e+00,
        -3.20000000e+00,  -3.10000000e+00,  -3.00000000e+00,
        -2.90000000e+00,  -2.80000000e+00,  -2.70000000e+00,
        -2.60000000e+00,  -2.50000000e+00,  -2.40000000e+00,
        -2.30000000e+00,  -2.20000000e+00,  -2.10000000e+00,
        -2.00000000e+00,  -1.90000000e+00,  -1.80000000e+00,
        -1.70000000e+00,  -1.60000000e+00,  -1.50000000e+00,
        -1.40000000e+00,  -1.30000000e+00,  -1.20000000e+00,
        -1.10000000e+00,  -1.00000000e+00,  -9.00000000e-01,
        -8.00000000e-01,  -7.00000000e-01,  -6.00000000e-01,
        -5.00000000e-01,  -4.00000000e-01,  -3.00000000e-01,
        -2.00000000e-01,

In [43]:
xs,ys=np.meshgrid(points,points)
xs

array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       ..., 
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]])

In [46]:
import matplotlib.pyplot as plt
z=np.sqrt(xs**2+ys**2)
z
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()
plt.title("sss")

Text(0.5,1,'sss')

### 12 将条件逻辑表达为数组运算


In [47]:
x=np.array([1.1,1.2,1.3,1.4,1.5])
y=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=np.where(cond,x,y)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [ ]:
s