## 1、ndarray

In [14]:
# 引入numpy
import numpy as np
#多维数组
array1=[6,7.5,8,0,1]
#通过array函数创建数组
data1=np.array(array1)
print(data1)
data1.shape

[ 6.   7.5  8.   0.   1. ]


(5,)

## 2嵌套序列


In [15]:
array2=[[1,2,3,4],[5,6,7,8,9]]
array21=[[1,2,3,4],[5,6,7,8]]
print(array2)
data2=np.array(array2)
print(data2)
print(np.array(array2))
array2
data2

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]


array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 9])], dtype=object)

## 3 查看类型

In [22]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
arr2
arr2.dtype


dtype('int32')

## 4 全0或全1数组

In [28]:
# 全0数组
np.zeros(10)
#
np.empty((2,3,2))
#对角线为1
# 的5*5方阵
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## 5 range 生成数组

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 5.1 ndarray的数据类型与显示转换

In [35]:
#转为浮点类型
arr1=np.array([1,2,3],dtype=np.float64)
print(arr1)
arr1.dtype
#显示类型转换
arr2=arr1.astype(np.int32)
print(arr2)

[ 1.  2.  3.]
[1 2 3]


## 6 数组和标量之间的运算

In [40]:
arr=np.array([[1,2,3,],[4,5,6]])
print(arr)
arr

# 自相乘
arr*arr
#每个位置上加2
arr+2

[[1 2 3]
 [4 5 6]]


array([[3, 4, 5],
       [6, 7, 8]])

## 7 基本的索引和切片

### 7.1 切片索引是浅拷贝

In [47]:
arr=np.arange(15)

print(arr)
# 索引从0开始计数
arr[3]
# 切片
# 参数1：起始位置下标
# 参数2：终止位置下标-1
# 数组切片是原始数组的视图
arr[3:5]=[100,101]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  0   1   2 100 101   5   6   7   8   9  10  11  12  13  14]


In [50]:
# 对数组进行副本复制
new_arr=arr[5:8].copy()
# 修改副本的值对原来的数组没有影响
new_arr[0]=300
print("new arr %s"%new_arr)
print("arr%s"%arr)

new arr [300   6   7]
arr[  0   1   2 100 101   5   6   7   8   9  10  11  12  13  14]


### 7.2 多维数组

In [54]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
# 取出索引为1的一行数据
arr2d[1]
# 取出二维数组中的某一个值
# 两种表现方式哪种都可以
arr2d[2,2]
arr2d[2][2]

9

#### (1)多维数组的切片索引

In [62]:
print(arr2d)
# 注意使用:x的方式x是下标减1的位置
arr2d[:2]
arr2d[:-2]
arr2d[:2,1:]
print(arr2d[1][:1])

# 选取第一列数据
arr2d[:,:1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4]


array([[1],
       [4],
       [7]])

## 8 布尔类型索引

In [67]:
names=np.array(['a1','b2','c3','d4','e5','f6','g7'])
data=np.random.randn(7,4)
print(data)
print(names=='a1')
data[names=='a1']

[[ 0.80435353 -1.10685336 -0.12452156  1.53407249]
 [-0.36458122 -0.73551516  0.2246557   0.73157827]
 [ 0.38313507  0.23936579  0.61708846  0.43514976]
 [ 1.2167821   2.29814979  0.33238843  0.88219711]
 [ 0.26060688 -0.7538822  -0.51636376  1.01926849]
 [ 0.87633345  0.54792549  0.45666567  0.3203654 ]
 [-0.969305   -0.53440768 -0.3789073  -1.32473732]]
[ True False False False False False False]


array([[ 0.80435353, -1.10685336, -0.12452156,  1.53407249]])