# 科学计算库NumPy

In [1]:
import numpy as np

## 1. 创建Array

In [2]:
my_list = [1, 2, 3]
x = np.array(my_list)

print('列表：', my_list)
print('Array: ', x)
print(x.shape,x.dtype)

列表： [1, 2, 3]
Array:  [1 2 3]
(3,) int32


In [3]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m)
print('shape: ', m.shape)
# 查看类型
print('type',m.dtype)

[[1 2 3]
 [4 5 6]]
shape:  (2, 3)
type int32


In [4]:
n = np.arange(0, 30, 2)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


n = n.reshape(3, 5)
print('reshape后: ')
print(n)

In [10]:
# 
# 创建指定长度或形状的全0或全1数组
# 里面使用的是元组
print('ones:\n', np.ones((3, 2)))
print('4*2\n',np.ones((4,2)))

print('zeros:\n', np.zeros((3, 2)))
print('eye:\n', np.eye(3))
print('empty\n',np.empty((2,3,4)))
print('diag:\n', np.diag(my_list))

ones:
 [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
4*2
 [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
zeros:
 [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
eye:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
empty
 [[[  2.31597830e+251   2.28896110e+243   1.39565102e-258   2.19993033e-152]
  [  3.68205014e+180   2.31634004e-152   2.42766851e-154   7.69843740e+218]
  [  5.98189658e-154   4.47593816e-091   6.01334512e-154   1.96086546e+243]]

 [[  1.39310750e-258   6.01347002e-154   9.13612771e+242   5.98129759e-154]
  [  1.06758000e+224   4.46811730e-091   5.98149672e-154   1.94862405e-153]
  [  1.90118402e-094   5.98185668e-154   8.58769271e+227   9.13607823e+242]]]
diag:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [17]:
print('*操作：\n', np.array([1, 2, 3] * 3))
print('repeat：\n', np.repeat([1, 2, 3], 3))

*操作：
 [1 2 3 1 2 3 1 2 3]
repeat：
 [1 1 1 2 2 2 3 3 3]


In [25]:
p1 = np.ones((3, 3))
p2 = np.arange(9).reshape(3, 3)
print('纵向叠加: \n', np.vstack((p1, p2)))
print('横向叠加: \n', np.hstack((p1, p2)))

纵向叠加: 
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
横向叠加: 
 [[ 1.  1.  1.  0.  1.  2.]
 [ 1.  1.  1.  3.  4.  5.]
 [ 1.  1.  1.  6.  7.  8.]]


# 数组与标量之间的运算

In [12]:
myarray=np.array([[1,2,3],[4,5,6]])
print(myarray)
myarray.astype(np.float64)

[[1 2 3]
 [4 5 6]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

## 2. Array操作

In [26]:
print('p1: \n', p1)
print('p2: \n', p2)

print('p1 + p2 = \n', p1 + p2)
print('p1 * p2 = \n', p1 * p2)
print('p2^2 = \n', p2 ** 2)
print('p1.p2 = \n', p1.dot(p2))

p1: 
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
p2: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
p1 + p2 = 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
p1 * p2 = 
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
p2^2 = 
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
p1.p2 = 
 [[  9.  12.  15.]
 [  9.  12.  15.]
 [  9.  12.  15.]]


In [29]:
p3 = np.arange(6).reshape(2, 3)
print('p3形状: ', p3.shape)
print(p3)
p4 = p3.T
print('转置后p3形状: ', p4.shape)
print(p4)

p3形状:  (2, 3)
[[0 1 2]
 [3 4 5]]
转置后p3形状:  (3, 2)
[[0 3]
 [1 4]
 [2 5]]


In [30]:
print('p3数据类型:', p3.dtype)
print(p3)

p5 = p3.astype('float')
print('p5数据类型:', p5.dtype)
print(p5)

p3数据类型: int32
[[0 1 2]
 [3 4 5]]
p5数据类型: float64
[[ 0.  1.  2.]
 [ 3.  4.  5.]]


In [7]:
import numpy as np
a = np.array([-4, -2, 1, 3, 5,7])
b=a.reshape(3,2)
print(a)
print(b)
print('sum: ', a.sum())
print('b sum',b.sum())
print('min: ', a.min())
print('max: ', a.max())
print('mean: ', a.mean())
print('std: ', a.std())
print('argmax: ', a.argmax())
print('argmin: ', a.argmin())

[-4 -2  1  3  5  7]
[[-4 -2]
 [ 1  3]
 [ 5  7]]
sum:  10
b sum 10
min:  -4
max:  7
mean:  1.66666666667
std:  3.81517438075
argmax:  5
argmin:  0


## 3. 索引与切片

In [39]:
# 一维array
s = np.arange(13) ** 2
print('s: ', s)
print('s[0]: ', s[0])
print('s[4]: ', s[4])
print('s[0:3]: ', s[0:3])
print('s[[0, 2, 4]]: ', s[[0, 2, 4]])

s:  [  0   1   4   9  16  25  36  49  64  81 100 121 144]
s[0]:  0
s[4]:  16
s[0:3]:  [0 1 4]
s[[0, 2, 4]]:  [ 0  4 16]


In [43]:
# 二维array
r = np.arange(36).reshape((6, 6))
print('r: \n', r)
print('r[2, 2]: \n', r[2, 2])
print('r[3, 3:6]: \n', r[3, 3:6])

r: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
r[2, 2]: 
 14
r[3, 3:6]: 
 [21 22 23]


In [46]:
# 过滤
print(r[r > 30])

# 将大于30的数赋值为30
r[r > 30] = 30
print(r)

[31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [48]:
# copy()操作
r2 = r[:3, :3]
print(r2)

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [49]:
# 将r2内容设置为0
r2[:] = 0

# 查看r的内容
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [50]:
r3 = r.copy()
r3[:] = 0
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## 4. 遍历 Array

In [51]:
t = np.random.randint(0, 10, (4, 3))
print(t)

[[6 0 8]
 [6 2 9]
 [2 4 2]
 [7 4 6]]


In [53]:
for row in t:
    print(row)

[6 0 8]
[6 2 9]
[2 4 2]
[7 4 6]


In [54]:
# 使用enumerate()
for i, row in enumerate(t):
    print('row {} is {}'.format(i, row))

row 0 is [6 0 8]
row 1 is [6 2 9]
row 2 is [2 4 2]
row 3 is [7 4 6]


In [55]:
t2 = t ** 2
print(t2)

[[36  0 64]
 [36  4 81]
 [ 4 16  4]
 [49 16 36]]


In [56]:
# 使用zip对两个array进行遍历计算
for i, j in zip(t, t2):
    print('{} + {} = {}'.format(i, j, i + j))

[6 0 8] + [36  0 64] = [42  0 72]
[6 2 9] + [36  4 81] = [42  6 90]
[2 4 2] + [ 4 16  4] = [ 6 20  6]
[7 4 6] + [49 16 36] = [56 20 42]
